config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  root to: "home#index"
  resources :future_books
  get "home/contact"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/future_book.rb
class FutureBook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
#  allow_browser versions: :modern
# end
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # ** to readd the login remove the comment below #
  # before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # actions show,edit,update,delete
  before_action :set_book, only: %i[ show edit update destroy ]
  # initializes the repository in one go without repeating throughout the page
  before_action :set_repository

  # GET /books or /books.json
  def index
    # Creating instance of repository
    # @book_repository = BookRepository.new

    # Uses repository to get books
    @books = @book_repository.all
    # @books = Book.all
  end

  # show 
  def show
  end

  # new 
  def new
    @book = Book.new
  end

  # edit 
  def edit
  end

  # create 
  def create
    # @book = Book.new(book_params)

    # new repository instance
    # @book_repository =BookRepository.new
    # create new book with repository
    @book = @book_repository.create(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  #  update 
  def update
    # new repository instance
    # @book_repository =BookRepository.new

    respond_to do |format|
      # if @book.update(book_params)
      # repository updates the book
      if @book_repository.update(@book, book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE 
  def destroy
    # @book.destroy!

    # new repository instance
    # @book_repository =BookRepository.new
    # delete book with repository
    @book_repository.delete(@book)

    respond_to do |format|
      format.html { redirect_to books_path, status: :see_other, notice: "Book was successfully Deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      # @book = Book.find(params.expect(:id))
      # located book by id
      @book = Book.find(params[:id])
    end

    # initializes the repository at the before_action line at the top of the page
    def set_repository
      @book_repository = BookRepository.new
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.expect(book: [ :title, :author, :genre, :book_description, :book_cost ])
    end
end

app/controllers/future_books_controller.rb
class FutureBooksController < ApplicationController
    def index
        #get all books
        @future_books = FutureBook.all 
        # creates instance for the form
        @future_book = FutureBook.new 
    end
    
    # creates  post for future book to be added
    def create
        #instance of new book with parameters
        @future_book = FutureBook.new(future_book_params)

        #if statement to check book and display when saved
        if @future_book.save
            @future_books = FutureBook.all 
            render :index
        else
            @future_books = FutureBook.all 
            render :index      
        end    
    end    

    private
        # Only allow a list of trusted parameters through.

        def future_book_params
            params.require(:future_book).permit(:title, :author, :status, :note)
        end    
    

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/future_books_helper.rb
module FutureBooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %> class="bookContent"">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= book.genre %>
  </p>

  <p>
    <strong>Book description:</strong>
    <%= book.book_description %>
  </p>

  <p>
    <strong>Book cost:</strong>
    <%= book.book_cost %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <div class="formContainer">
     <% if book.errors.any? %>
      <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      </div>
     <% end %>

     <div>
       <%= form.label :title, style: "display: block" %>
       <%= form.text_field :title %>
     </div>

     <div>
       <%= form.label :author, style: "display: block" %>
       <%= form.text_field :author %>
     </div>

     <div>
       <%= form.label :genre, style: "display: block" %>
       <%= form.text_field :genre %>
     </div>

     <div>
       <%= form.label :book_description, style: "display: block" %>
       <%= form.text_field :book_description %>
     </div>

     <div>
       <%= form.label :book_cost, style: "display: block" %>
       <%= form.number_field :book_cost %>
     </div>
     <br>
     <div>
       <%= form.submit %>
     </div>
  </div>  
<% end %>

app/views/books/edit.html.erb
<% content_for :title, "Editing book" %>

<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Books" %>

<title>Books</title>
<h3> Marvell at your Greatness </h3>
<p>

It doesnt matter the size of the book, you have made the effect, why not add your read book to the list. <br>
<%= link_to "Add ", new_book_path %> another book to your Collection
</P>
<br>


<div >
  <% @books.each do |book| %>
    <%= render book  %>
    <p>
      <%= link_to "view", book %> this book
    </p><br>
  <% end %>
</div>
<br>

app/views/books/new.html.erb
<% content_for :title, "New book" %>

<title>New book</title>
<br>
<p>Complete your book form below to be able to add your book to your growing collection </p>




<%= render "form", book: @book %>

<br>

<div>
 Open your Book <%= link_to "Collection", books_path %>
</div>
<br>

<%= image_tag "addbookimage.png"%>  <!--https://www.pexels.com/photo/books-filed-neatly-on-shelves-1907785/-->
<%= image_tag "addbookimage2.png"%> <!--https://www.pexels.com/photo/string-lights-on-a-book-1791742/-->

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Edit", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Delete", @book, method: :delete %>
</div>

app/views/future_books/index.html.erb
<title>Need to Read Books</title>

<%= form_with model: @future_book, url: future_books_path, local: true do |form| %>
    <% if @future_book.errors.any? %>
      <div class="errors">
        <h2>Errors:</h2>
        <ul>
          <% @future_book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </div>
  
    <div>
      <%= form.label :author %><br>
      <%= form.text_field :author %>
    </div>
  
    <div>
      <%= form.label :status %><br>
      <%= form.text_field :status %>
    </div>
    <div>
    <%= form.label :note %><br>
    <%= form.text_field :note %>
  </div>
    <br>
    <div>
      <%= form.submit 'Add Book to List' %>
    </div>
  <% end %>
  
 
  <br>
  <h3>The one place to store your need to Books List</h3>
  <p> We dont judge at Book Spot no matter how long a book has been on your list </p>
  <p> Please Refresh Page if book doesnt appear below</p>
  <br>

  <ul>
    <% @future_books.each do |book| %>
      <li>
        <%= book.title %> by <%= book.author %> |
         Status: <%= book.status %> |
        <%= "  Note: #{book.note}" if book.note.present? %>
       </li>
    <% end %>
  </ul>

 

app/views/home/_footer.html.erb
<footer class="footer navbar-fixed-bottom  footnav">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); flex-shrink: 0;" >

© 2021 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
    </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light  headnav">
 <%= link_to 'Book Spot', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
         <li class="nav-item">
             <%= link_to "Add Book", new_book_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Book Collection", books_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Need to Read Books", future_books_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Contact Page", home_contact_path, class:"nav-link" %>
        </li>
    
    </div>

 
</nav>

app/views/home/contact.html.erb
<title>Contact us page</title>
<br>
<h4> Complete contact form below </h4>
<br>
<p> We have a estimate 24 hr return time </p>
<br>
<div class="contactContainer">

    <form action="">
        <label for="fName">First Name: </label>
        <input type="fName" name="fName" placeholder="First Name" required> <br>
        <label for="fName">Last Name: </label>
        <input type="fName" name="lName" placeholder="Last Name" required> <br>
        <label for="email">Email:</label>
        <input type="email" name="email" placeholder="Email" > <br>
        <label for="subject">Subject:</label><br>
        <textarea id="subject" name="subject" placeholder="Write something.." ></textarea>
        <br>
        <button id="submit" type="submit">Submit</button>
    </form>
</div>

<br>
    <%= image_tag "n2rimage.png"%>
    <%= image_tag "contactbooks.png"%>
   
     <br>

app/views/home/index.html.erb
<title>Book Spot Home</title>


<h3>The place where you can save your favourite books by adding to your collection</h3>
<p>Add your book to a Collection or treat as A Wish List</P>
<br>


<%= image_tag "homeImage.png"%>



<p>
Book Spot the one location where you can store your just read books. It can be a pain to forget a book and then try to remeber a name or author.
This Book Spot takes that pain away, with the simple tool of being able to add your book to a collection or even a wish list of whats next to read.
The way you can use this application is wholely up to you the user.
So happy reading, and what ever you imagine can come through.
<br><br>
<!-#https://loremipsum.io/generator?n=5&t=p -->
Lorem ipsum odor amet, consectetuer adipiscing elit. Eget potenti platea nec fusce arcu nulla ex. 
Suscipit porta natoque egestas placerat praesent. Turpis malesuada sapien lacinia urna leo pharetra.
Rhoncus mi pretium etiam tellus ligula. Lorem duis fringilla torquent commodo tempor etiam posuere nisi.
Hendrerit scelerisque nostra placerat vitae risus ridiculus. Posuere sed adipiscing sodales nisi odio, netus condimentum ultrices. 
<br><br>
Luctus volutpat dui eget pulvinar consectetur feugiat. Vestibulum dapibus phasellus ornare mus convallis neque feugiat lacinia! Orci ante pretium tellus sed; torquent hendrerit. 
Massa est vestibulum gravida; cubilia penatibus ornare tincidunt vel. Tempor porttitor sollicitudin pharetra montes cubilia. Sem feugiat felis aenean cras; 
volutpat tincidunt nullam nulla maximus. Suscipit ante cras velit hendrerit gravida ullamcorper imperdiet tempor potenti. Ad arcu penatibus per quis vivamus neque nullam.
<br><br>
Finibus nibh lacus consequat, hendrerit finibus quisque leo felis. 
Tincidunt dapibus gravida vel euismod fames scelerisque. 
Pellentesque viverra curabitur justo eleifend morbi non vitae velit.
 Molestie eros aliquam penatibus pretium convallis sociosqu vitae mollis? Orci libero dictum quam pellentesque diam morbi sem magnis. 
 Nisl dui feugiat est, tellus montes mus interdum volutpat. Aenean venenatis pharetra augue, curabitur volutpat vivamus. 
 Ac gravida vel turpis imperdiet scelerisque torquent. Dis nascetur nam feugiat leo scelerisque nibh sodales.
</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Below is added from orginal part to bootstrap -->
    <title>Book Spot</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>

  </head>
  <body>
   
    <%= render 'home/header' %>


    <div class ="container">
   

   

      <%= yield %> 
      
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    
      </div>
    <%= render 'home/footer' %>
     <!-- till above  is added from orginal part to bootstrap -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>